### ISSUE TITLE
Next state not found should return useful error message

### ISSUE THREAD

**Issue by girikuncoro** [kata-ai/kata-cli#35]
In my flow, I made a mistake by specifying transition to nextState which doesnt exist
```
states:
  init:
    initial: true
    transitions:
      showTrivia:  # showTrivia doesn't exist
        condition: "intent == 'trivia'"
```

when I trigger the flow from `kata console`, the error says:
```
console> text('mau main')
'Cannot read property \'id\' of null'
```

might be more useful by saying: `cannot transit to showTrivia state from init state`. I would envision a proper yaml validator before pushing bot definition to be important for users.
